# Generated by Django 4.1 on 2022-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('state', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
                ('taskTitle', models.CharField(max_length=100, verbose_name='Название задания')),
                ('taskText', models.TextField(verbose_name='Тект задания')),
            ],
        ),
    ]
