# Generated by Django 4.1 on 2022-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstasks',
            name='task_id',
            field=models.IntegerField(default=0, verbose_name='внутреннее id задания'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='state',
            field=models.CharField(max_length=50, verbose_name='состояние'),
        ),
    ]
